enabled: false
#namespace: monitoring
chart_version: "19.7.2"
volume_size: "3Gi"
volume_storage_class: "standard"
scrape_configs:
  - job_name: internet-gateway
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - gateway.home.mehringer.com:9100
  - job_name: network-storage
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - core.home.mehringer.com:9100
node_exporter_host_root_fs_mount: false
